"""add pattern column to transactions

Revision ID: 3cb76b43cb58
Revises: 79bb0df5aab1
Create Date: 2026-09-17 09:26:46.124449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb76b43cb58'
down_revision: Union[str, Sequence[str], None] = '79bb0df5aab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('pattern', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'pattern')
    # ### end Alembic commands ###
